handicap: 90
game_duration: 15
gift_compass: true
hunt_in_night: true
lang: "en_us"

en_us:
  gift_compass_name: "&3Compass to ruined portal"
  game_doesnt_start: "&4Game doesn't start!"
  enter_instructions: "Game will start, when somebody use &e/start&f (became survivor)"
  game_started: "&4Game starts! RUN, SURV, RUN!"
  handicup_ends: "&5Handicup ends after %d %s"
  handicup_doesnt_end: "&4Handicup doesn't end!"
  surv_die_before_hunt_starts: "&1Surv dies before hunt starts! Make fun of him!"
  hunt_starts: "&2Hunt began!"
  game_ends_after: "&4Survivor wins after %d %s"
  survivor_wins: "&2Survivor wins!"
  hunters_win: "&4Hunts win!"
  sec: "sec"
  min: "min"

ru_ru:
  gift_compass_name: "&3Компас на разрушенный портал"
  game_doesnt_start: "&4Игра ещё не началась!"
  enter_instructions: "Игра начнётся когда кто-нибудь станет жужелицей написав &e/start&f"
  game_started: "&4Игра началась! БЕГИ, ЖУЖЕЛИЦА, БЕГИ!!!"
  handicup_ends: "&5Фора закончится через %d %s"
  handicup_doesnt_end: "&4Жужелице дана фора. Она ещё не закончилась!"
  surv_die_before_hunt_starts: "&1Оно погибло до начала игры! Насмехайтесь над ним!"
  hunt_starts: "&2Открытие охоты!"
  game_ends_after: "&4Жужелица победит через %d %s"
  survivor_wins: "&2Жужелица победила!"
  hunters_win: "&4Охотники победили!"
  sec: "сек"
  min: "мин"